.catalog:
  name: "Shard MongoDB Rancher Template"
  version: "v1.0.0"
  description: |
    Shard MongoDB Rancher Template Cluster
  questions:
    - variable: MONGO_VERSION
      label: "MongoDB version"
      type: enum
      options:
        - mongo:4.0.9
        - mongo:3.6.12
      default: mongo:4.0.9
      required: true
    - variable: MONGODB_KEYFILE
      label: "MongoDB Keyfile"
      type: multiline
      required: true
      description: "Generar con: openssl rand -base64 756"
    - variable: MONGO_INITDB_ROOT_USERNAME
      label: "Username para el usuario administrador(Optional)"
      type: string
      default: "admin"
      required: false
    - variable: MONGO_INITDB_ROOT_PASSWORD
      label: "Password para el usuario administrador"
      type: password
      required: true
    - variable: MONGODB_DBNAME
      label: "Nombre DDBB (Optional)"
      type: string
      required: false
    - variable: MONGOS_PORT
      label: "Puerto Mongos"
      type: int
      required: true
      default: "27017"
    - variable: MONGOD_PORT
      label: "puesrto Mongod (Optional)"
      type: int
      required: false
    - variable: "ARBITER_ENABLED"
      label: "Habilitar árbitro"
      description: "Habilitar árbitro para Mongod ReplicaSet."
      type: boolean
      required: true
      default: true
    - variable: "CONFIGSVR_ENABLED"
      label: "Habilitar ConfigServer"
      description: "Habilitar ConfigServer Sharded."
      type: boolean
      required: true
      default: true
    - variable: "MONGOS_ENABLED"
      label: "Habilitar Mongos"
      description: "Habilitar Mongos Sharded."
      type: boolean
      required: true
      default: true
    - variable: "MONGOD_SCALE"
      label: "Nodos de Mongod"
      description: "Número de nodos Mongod a escalar. Un nodo por cada host"
      type: int
      required: true
      default: 2
    - variable: "CONFIGSVR_SCALE"
      label: "NOdos de ConfigServer"
      description: "Número de nodos ConfigServer a escalar. Un nodo por cada host"
      type: int
      required: true
      default: 3
    - variable: MONGOD_RS_NAME
      label: "Nombre del Mongod ReplicaSet"
      type: string
      required: true
      default: "rs1"
    - variable: CONFIGSVR_RS_NAME
      label: "Nombre del Configsvr ReplicaSet"
      type: string
      required: true
      default: "configsvr_rs1"
    - variable: MONGOD_HOST_LABEL
      label: "Host label para nodos mongod(Optional)"
      type: string
      required: false
    - variable: ARBITER_HOST_LABEL
      label: "Host label para nodos árbitro (Optional)"
      type: string
      required: false
    - variable: CONFIGSVR_HOST_LABEL
      label: "Host label para nodos configserver (Optional)"
      type: string
      required: false
    - variable: MONGOS_HOST_LABEL
      label: "Host label para nodos mongos (Optional)"
      type: string
      required: false
    - variable: MONGOD_VOLUME_PATH
      label: Ruta del volúmen de los nodos mongod
      description: Almacenamiento de mongod data.
      type: string
      required: false
    - variable: ARBITER_VOLUME_PATH
      label: Ruta del volúmen de los nodos árbitro (Optional)
      description: Almacenamiento de árbitro data.
      type: string
      required: false
    - variable: CONFIGSVR_VOLUME_PATH
      label: Ruta del volúmen de los nodos ConfigServer
      description: Almacenamiento de ConfigServer data.
      type: string
      required: false

version: '2'
services:
  mongod:
    scale: ${MONGOD_SCALE}
    start_on_create: true
    retain_ip: true
  configsvr:
    scale: ${CONFIGSVR_SCALE}
    start_on_create: true
    retain_ip: true
  mongos:
    scale: 1
    start_on_create: true
    retain_ip: true
